---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeprober.erda.cloud
  resources:
  - probes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeprober.erda.cloud
  resources:
  - probes/finalizers
  verbs:
  - update
- apiGroups:
  - kubeprober.erda.cloud
  resources:
  - probes/status
  verbs:
  - get
  - patch
  - update
